In [19]:
import numpy as np

edge = 5
my_range = edge**2

ray = np.arange(my_range).reshape(edge, edge)
print(ray)
print('\n')

'''
subr = ray[1:,0:-1]
print(subr)
print('\n')
'''

k = -1

if (k < 0):
    subr =(ray[abs(k):, 0:k])
    subr[np.diag_indices_from(subr)] -= 100
    print(subr)
    print('\n')


elif(k > 0):
    subr = ray [0: -k, k: ]
    print(subr)
    subr[np.diag_indices_from(subr)] +=100
    print(subr)
    print('\n')
    
else:
    ray[np.diag_indices_from(ray)] += 200
    
print(ray)
        



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


[[105   6   7   8]
 [ 10 111  12  13]
 [ 15  16 117  18]
 [ 20  21  22 123]]


[[  0   1   2   3   4]
 [105   6   7   8   9]
 [ 10 111  12  13  14]
 [ 15  16 117  18  19]
 [ 20  21  22 123  24]]
